import React, { Component } from 'react';
import {Dropdown, Form} from "semantic-ui-react";
import PropTypes from 'prop-types';

class IconInput extends Component {
    tagOptions = [
        {key: '500px',text: '500px',value: '500px',icon: '500px',},
        {key: 'accessible',text: 'accessible',value: 'accessible',icon: 'accessible',},
        {key: 'accusoft',text: 'accusoft',value: 'accusoft',icon: 'accusoft',},
        {key: 'address book',text: 'address book',value: 'address book',icon: 'address book',},
        {key: 'address book outline',text: 'address book outline',value: 'address book outline',icon: 'address book outline',},
        {key: 'adjust',text: 'adjust',value: 'adjust',icon: 'adjust',},
        {key: 'adn',text: 'adn',value: 'adn',icon: 'adn',},
        {key: 'adversal',text: 'adversal',value: 'adversal',icon: 'adversal',},
        {key: 'affiliatetheme',text: 'affiliatetheme',value: 'affiliatetheme',icon: 'affiliatetheme',},
        {key: 'algolia',text: 'algolia',value: 'algolia',icon: 'algolia',},
        {key: 'align center',text: 'align center',value: 'align center',icon: 'align center',},
        {key: 'align justify',text: 'align justify',value: 'align justify',icon: 'align justify',},
        {key: 'align left',text: 'align left',value: 'align left',icon: 'align left',},
        {key: 'align right',text: 'align right',value: 'align right',icon: 'align right',},
        {key: 'amazon',text: 'amazon',value: 'amazon',icon: 'amazon',},
        {key: 'amazon pay',text: 'amazon pay',value: 'amazon pay',icon: 'amazon pay',},
        {key: 'ambulance',text: 'ambulance',value: 'ambulance',icon: 'ambulance',},
        {key: 'american sign language interpreting',text: 'american sign language interpreting',value: 'american sign language interpreting',icon: 'american sign language interpreting',},
        {key: 'amilia',text: 'amilia',value: 'amilia',icon: 'amilia',},
        {key: 'anchor',text: 'anchor',value: 'anchor',icon: 'anchor',},
        {key: 'android',text: 'android',value: 'android',icon: 'android',},
        {key: 'angellist',text: 'angellist',value: 'angellist',icon: 'angellist',},
        {key: 'angle double down',text: 'angle double down',value: 'angle double down',icon: 'angle double down',},
        {key: 'angle double left',text: 'angle double left',value: 'angle double left',icon: 'angle double left',},
        {key: 'angle double right',text: 'angle double right',value: 'angle double right',icon: 'angle double right',},
        {key: 'angle double up',text: 'angle double up',value: 'angle double up',icon: 'angle double up',},
        {key: 'angle down',text: 'angle down',value: 'angle down',icon: 'angle down',},
        {key: 'angle left',text: 'angle left',value: 'angle left',icon: 'angle left',},
        {key: 'angle right',text: 'angle right',value: 'angle right',icon: 'angle right',},
        {key: 'angle up',text: 'angle up',value: 'angle up',icon: 'angle up',},
        {key: 'angrycreative',text: 'angrycreative',value: 'angrycreative',icon: 'angrycreative',},
        {key: 'angular',text: 'angular',value: 'angular',icon: 'angular',},
        {key: 'app store',text: 'app store',value: 'app store',icon: 'app store',},
        {key: 'app store ios',text: 'app store ios',value: 'app store ios',icon: 'app store ios',},
        {key: 'apper',text: 'apper',value: 'apper',icon: 'apper',},
        {key: 'apple',text: 'apple',value: 'apple',icon: 'apple',},
        {key: 'apple pay',text: 'apple pay',value: 'apple pay',icon: 'apple pay',},
        {key: 'archive',text: 'archive',value: 'archive',icon: 'archive',},
        {key: 'arrow alternate circle down',text: 'arrow alternate circle down',value: 'arrow alternate circle down',icon: 'arrow alternate circle down',},
        {key: 'arrow alternate circle down outline',text: 'arrow alternate circle down outline',value: 'arrow alternate circle down outline',icon: 'arrow alternate circle down outline',},
        {key: 'arrow alternate circle left',text: 'arrow alternate circle left',value: 'arrow alternate circle left',icon: 'arrow alternate circle left',},
        {key: 'arrow alternate circle left outline',text: 'arrow alternate circle left outline',value: 'arrow alternate circle left outline',icon: 'arrow alternate circle left outline',},
        {key: 'arrow alternate circle right',text: 'arrow alternate circle right',value: 'arrow alternate circle right',icon: 'arrow alternate circle right',},
        {key: 'arrow alternate circle right outline',text: 'arrow alternate circle right outline',value: 'arrow alternate circle right outline',icon: 'arrow alternate circle right outline',},
        {key: 'arrow alternate circle up',text: 'arrow alternate circle up',value: 'arrow alternate circle up',icon: 'arrow alternate circle up',},
        {key: 'arrow alternate circle up outline',text: 'arrow alternate circle up outline',value: 'arrow alternate circle up outline',icon: 'arrow alternate circle up outline',},
        {key: 'arrow circle down',text: 'arrow circle down',value: 'arrow circle down',icon: 'arrow circle down',},
        {key: 'arrow circle left',text: 'arrow circle left',value: 'arrow circle left',icon: 'arrow circle left',},
        {key: 'arrow circle right',text: 'arrow circle right',value: 'arrow circle right',icon: 'arrow circle right',},
        {key: 'arrow circle up',text: 'arrow circle up',value: 'arrow circle up',icon: 'arrow circle up',},
        {key: 'arrow down',text: 'arrow down',value: 'arrow down',icon: 'arrow down',},
        {key: 'arrow left',text: 'arrow left',value: 'arrow left',icon: 'arrow left',},
        {key: 'arrow right',text: 'arrow right',value: 'arrow right',icon: 'arrow right',},
        {key: '',text: '',value: '',icon: '',},
        {key: 'arrow up',text: 'arrow up',value: 'arrow up',icon: 'arrow up',},
        {key: 'arrows alternate',text: 'arrows alternate',value: 'arrows alternate',icon: 'arrows alternate',},
        {key: 'arrows alternate horizontal',text: 'arrows alternate horizontal',value: 'arrows alternate horizontal',icon: 'arrows alternate horizontal',},
        {key: 'arrows alternate vertical',text: 'arrows alternate vertical',value: 'arrows alternate vertical',icon: 'arrows alternate vertical',},
        {key: 'assistive listening systems',text: 'assistive listening systems',value: 'assistive listening systems',icon: 'assistive listening systems',},
        {key: 'asterisk',text: 'asterisk',value: 'asterisk',icon: 'asterisk',},
        {key: 'asymmetrik',text: 'asymmetrik',value: 'asymmetrik',icon: 'asymmetrik',},
        {key: 'at',text: 'at',value: 'at',icon: 'at',},
        {key: 'audible',text: 'audible',value: 'audible',icon: 'audible',},
        {key: 'audio description',text: 'audio description',value: 'audio description',icon: 'audio description',},
        {key: 'autoprefixer',text: 'autoprefixer',value: 'autoprefixer',icon: 'autoprefixer',},
        {key: 'avianex',text: 'avianex',value: 'avianex',icon: 'avianex',},
        {key: 'aviato',text: 'aviato',value: 'aviato',icon: 'aviato',},
        {key: 'aws',text: 'aws',value: 'aws',icon: 'aws',},
        {key: 'backward',text: 'backward',value: 'backward',icon: 'backward',},
        {key: 'balance scale',text: 'balance scale',value: 'balance scale',icon: 'balance scale',},
        {key: 'ban',text: 'ban',value: 'ban',icon: 'ban',},
        {key: 'band aid',text: 'band aid',value: 'band aid',icon: 'band aid',},
        {key: 'bandcamp',text: 'bandcamp',value: 'bandcamp',icon: 'bandcamp',},
        {key: 'barcode',text: 'barcode',value: 'barcode',icon: 'barcode',},
        {key: 'bars',text: 'bars',value: 'bars',icon: 'bars',},
        {key: 'baseball ball',text: 'baseball ball',value: 'baseball ball',icon: 'baseball ball',},
        {key: 'basketball ball',text: 'basketball ball',value: 'basketball ball',icon: 'basketball ball',},
        {key: 'bath',text: 'bath',value: 'bath',icon: 'bath',},
        {key: 'battery empty',text: 'battery empty',value: 'battery empty',icon: 'battery empty',},
        {key: 'battery full',text: 'battery full',value: 'battery full',icon: 'battery full',},
        {key: 'battery half',text: 'battery half',value: 'battery half',icon: 'battery half',},
        {key: 'battery quarter',text: 'battery quarter',value: 'battery quarter',icon: 'battery quarter',},
        {key: 'battery three quarters',text: 'battery three quarters',value: 'battery three quarters',icon: 'battery three quarters',},
        {key: 'bed',text: 'bed',value: 'bed',icon: 'bed',},
        {key: 'beer',text: 'beer',value: 'beer',icon: 'beer',},
        {key: 'behance',text: 'behance',value: 'behance',icon: 'behance',},
        {key: 'behance square',text: 'behance square',value: 'behance square',icon: 'behance square',},
        {key: 'bell',text: 'bell',value: 'bell',icon: 'bell',},
        {key: 'bell outline',text: 'bell outline',value: 'bell outline',icon: 'bell outline',},
        {key: 'bell slash',text: 'bell slash',value: 'bell slash',icon: 'bell slash',},
        {key: 'bell slash outline',text: 'bell slash outline',value: 'bell slash outline',icon: 'bell slash outline',},
        {key: 'bicycle',text: 'bicycle',value: 'bicycle',icon: 'bicycle',},
        {key: 'bimobject',text: 'bimobject',value: 'bimobject',icon: 'bimobject',},
        {key: 'binoculars',text: 'binoculars',value: 'binoculars',icon: 'binoculars',},
        {key: 'birthday cake',text: 'birthday cake',value: 'birthday cake',icon: 'birthday cake',},
        {key: 'bitbucket',text: 'bitbucket',value: 'bitbucket',icon: 'bitbucket',},
        {key: 'bitcoin',text: 'bitcoin',value: 'bitcoin',icon: 'bitcoin',},
        {key: 'bity',text: 'bity',value: 'bity',icon: 'bity',},
        {key: 'black tie',text: 'black tie',value: 'black tie',icon: 'black tie',},
        {key: 'blackberry',text: 'blackberry',value: 'blackberry',icon: 'blackberry',},
        {key: 'blind',text: 'blind',value: 'blind',icon: 'blind',},
        {key: 'blogger',text: 'blogger',value: 'blogger',icon: 'blogger',},
        {key: 'blogger b',text: 'blogger b',value: 'blogger b',icon: 'blogger b',},
        {key: 'bluetooth',text: 'bluetooth',value: 'bluetooth',icon: 'bluetooth',},
        {key: 'bluetooth b',text: 'bluetooth b',value: 'bluetooth b',icon: 'bluetooth b',},
        {key: 'bold',text: 'bold',value: 'bold',icon: 'bold',},
        {key: 'bolt',text: 'bolt',value: 'bolt',icon: 'bolt',},
        {key: 'bomb',text: 'bomb',value: 'bomb',icon: 'bomb',},
        {key: 'book',text: 'book',value: 'book',icon: 'book',},
        {key: 'bookmark',text: 'bookmark',value: 'bookmark',icon: 'bookmark',},
        {key: 'bookmark outline',text: 'bookmark outline',value: 'bookmark outline',icon: 'bookmark outline',},
        {key: 'bowling ball',text: 'bowling ball',value: 'bowling ball',icon: 'bowling ball',},
        {key: 'box',text: 'box',value: 'box',icon: 'box',},
        {key: 'boxes',text: 'boxes',value: 'boxes',icon: 'boxes',},
        {key: 'braille',text: 'braille',value: 'braille',icon: 'braille',},
        {key: 'briefcase',text: 'briefcase',value: 'briefcase',icon: 'briefcase',},
        {key: 'btc',text: 'btc',value: 'btc',icon: 'btc',},
        {key: 'bug',text: 'bug',value: 'bug',icon: 'bug',},
        {key: 'building',text: 'building',value: 'building',icon: 'building',},
        {key: 'building outline',text: 'building outline',value: 'building outline',icon: 'building outline',},
        {key: 'bullhorn',text: 'bullhorn',value: 'bullhorn',icon: 'bullhorn',},
        {key: 'bullseye',text: 'bullseye',value: 'bullseye',icon: 'bullseye',},
        {key: 'buromobelexperte',text: 'buromobelexperte',value: 'buromobelexperte',icon: 'buromobelexperte',},
        {key: 'bus',text: 'bus',value: 'bus',icon: 'bus',},
        {key: 'buysellads',text: 'buysellads',value: 'buysellads',icon: 'buysellads',},
        {key: 'calculator',text: 'calculator',value: 'calculator',icon: 'calculator',},
        {key: 'calendar',text: 'calendar',value: 'calendar',icon: 'calendar',},
        {key: 'calendar alternate',text: 'calendar alternate',value: 'calendar alternate',icon: 'calendar alternate',},
        {key: 'calendar alternate outline',text: 'calendar alternate outline',value: 'calendar alternate outline',icon: 'calendar alternate outline',},
        {key: 'calendar check',text: 'calendar check',value: 'calendar check',icon: 'calendar check',},
        {key: 'calendar check outline',text: 'calendar check outline',value: 'calendar check outline',icon: 'calendar check outline',},
        {key: 'calendar minus',text: 'calendar minus',value: 'calendar minus',icon: 'calendar minus',},
        {key: 'calendar minus outline',text: 'calendar minus outline',value: 'calendar minus outline',icon: 'calendar minus outline',},
        {key: 'calendar outline',text: 'calendar outline',value: 'calendar outline',icon: 'calendar outline',},
        {key: 'calendar plus',text: 'calendar plus',value: 'calendar plus',icon: 'calendar plus',},
        {key: 'calendar plus outline',text: 'calendar plus outline',value: 'calendar plus outline',icon: 'calendar plus outline',},
        {key: 'calendar times',text: 'calendar times',value: 'calendar times',icon: 'calendar times',},
        {key: 'calendar times outline',text: 'calendar times outline',value: 'calendar times outline',icon: 'calendar times outline',},
        {key: 'camera',text: 'camera',value: 'camera',icon: 'camera',},
        {key: 'camera retro',text: 'camera retro',value: 'camera retro',icon: 'camera retro',},
        {key: 'car',text: 'car',value: 'car',icon: 'car',},
        {key: 'caret down',text: 'caret down',value: 'caret down',icon: 'caret down',},
        {key: 'caret left',text: 'caret left',value: 'caret left',icon: 'caret left',},
        {key: 'caret right',text: 'caret right',value: 'caret right',icon: 'caret right',},
        {key: 'caret square down',text: 'caret square down',value: 'caret square down',icon: 'caret square down',},
        {key: 'caret square down outline',text: 'caret square down outline',value: 'caret square down outline',icon: 'caret square down outline',},
        {key: 'caret square left',text: 'caret square left',value: 'caret square left',icon: 'caret square left',},
        {key: 'caret square left outline',text: 'caret square left outline',value: 'caret square left outline',icon: 'caret square left outline',},
        {key: 'caret square right',text: 'caret square right',value: 'caret square right',icon: 'caret square right',},
        {key: 'caret square right outline',text: 'caret square right outline',value: 'caret square right outline',icon: 'caret square right outline',},
        {key: 'caret square up',text: 'caret square up',value: 'caret square up',icon: 'caret square up',},
        {key: 'caret square up outline',text: 'caret square up outline',value: 'caret square up outline',icon: 'caret square up outline',},
        {key: 'caret up',text: 'caret up',value: 'caret up',icon: 'caret up',},
        {key: 'cart arrow down',text: 'cart arrow down',value: 'cart arrow down',icon: 'cart arrow down',},
        {key: 'cart plus',text: 'cart plus',value: 'cart plus',icon: 'cart plus',},
        {key: 'cc amazon pay',text: 'cc amazon pay',value: 'cc amazon pay',icon: 'cc amazon pay',},
        {key: 'cc amex',text: 'cc amex',value: 'cc amex',icon: 'cc amex',},
        {key: 'cc apple pay',text: 'cc apple pay',value: 'cc apple pay',icon: 'cc apple pay',},
        {key: 'cc diners club',text: 'cc diners club',value: 'cc diners club',icon: 'cc diners club',},
        {key: 'cc discover',text: 'cc discover',value: 'cc discover',icon: 'cc discover',},
        {key: 'cc jcb',text: 'cc jcb',value: 'cc jcb',icon: 'cc jcb',},
        {key: 'cc mastercard',text: 'cc mastercard',value: 'cc mastercard',icon: 'cc mastercard',},
        {key: 'cc paypal',text: 'cc paypal',value: 'cc paypal',icon: 'cc paypal',},
        {key: 'cc stripe',text: 'cc stripe',value: 'cc stripe',icon: 'cc stripe',},
        {key: 'cc visa',text: 'cc visa',value: 'cc visa',icon: 'cc visa',},
        {key: 'centercode',text: 'centercode',value: 'centercode',icon: 'centercode',},
        {key: 'certificate',text: 'certificate',value: 'certificate',icon: 'certificate',},
        {key: 'chart area',text: 'chart area',value: 'chart area',icon: 'chart area',},
        {key: 'chart bar',text: 'chart bar',value: 'chart bar',icon: 'chart bar',},
        {key: 'chart bar outline',text: 'chart bar outline',value: 'chart bar outline',icon: 'chart bar outline',},
        {key: 'chart line',text: 'chart line',value: 'chart line',icon: 'chart line',},
        {key: 'chart pie',text: 'chart pie',value: 'chart pie',icon: 'chart pie',},
        {key: 'check',text: 'check',value: 'check',icon: 'check',},
        {key: 'check circle',text: 'check circle',value: 'check circle',icon: 'check circle',},
        {key: 'check circle outline',text: 'check circle outline',value: 'check circle outline',icon: 'check circle outline',},
        {key: 'check square',text: 'check square',value: 'check square',icon: 'check square',},
        {key: 'check square outline',text: 'check square outline',value: 'check square outline',icon: 'check square outline',},
        {key: 'chess',text: 'chess',value: 'chess',icon: 'chess',},
        {key: 'chess bishop',text: 'chess bishop',value: 'chess bishop',icon: 'chess bishop',},
        {key: 'chess board',text: 'chess board',value: 'chess board',icon: 'chess board',},
        {key: 'chess king',text: 'chess king',value: 'chess king',icon: 'chess king',},
        {key: 'chess knight',text: 'chess knight',value: 'chess knight',icon: 'chess knight',},
        {key: 'chess pawn',text: 'chess pawn',value: 'chess pawn',icon: 'chess pawn',},
        {key: 'chess queen',text: 'chess queen',value: 'chess queen',icon: 'chess queen',},
        {key: 'chess rook',text: 'chess rook',value: 'chess rook',icon: 'chess rook',},
        {key: 'chevron circle down',text: 'chevron circle down',value: 'chevron circle down',icon: 'chevron circle down',},
        {key: 'chevron circle left',text: 'chevron circle left',value: 'chevron circle left',icon: 'chevron circle left',},
        {key: 'chevron circle right',text: 'chevron circle right',value: 'chevron circle right',icon: 'chevron circle right',},
        {key: 'chevron circle up',text: 'chevron circle up',value: 'chevron circle up',icon: 'chevron circle up',},
        {key: 'chevron down',text: 'chevron down',value: 'chevron down',icon: 'chevron down',},
        {key: 'chevron left',text: 'chevron left',value: 'chevron left',icon: 'chevron left',},
        {key: 'chevron right',text: 'chevron right',value: 'chevron right',icon: 'chevron right',},
        {key: 'chevron up',text: 'chevron up',value: 'chevron up',icon: 'chevron up',},
        {key: 'child',text: 'child',value: 'child',icon: 'child',},
        {key: 'chrome',text: 'chrome',value: 'chrome',icon: 'chrome',},
        {key: 'circle',text: 'circle',value: 'circle',icon: 'circle',},
        {key: 'circle notch',text: 'circle notch',value: 'circle notch',icon: 'circle notch',},
        {key: 'circle outline',text: 'circle outline',value: 'circle outline',icon: 'circle outline',},
        {key: 'clipboard',text: 'clipboard',value: 'clipboard',icon: 'clipboard',},
        {key: 'clipboard check',text: 'clipboard check',value: 'clipboard check',icon: 'clipboard check',},
        {key: 'clipboard list',text: 'clipboard list',value: 'clipboard list',icon: 'clipboard list',},
        {key: 'clipboard outline',text: 'clipboard outline',value: 'clipboard outline',icon: 'clipboard outline',},
        {key: 'clock',text: 'clock',value: 'clock',icon: 'clock',},
        {key: 'clock outline',text: 'clock outline',value: 'clock outline',icon: 'clock outline',},
        {key: 'clone',text: 'clone',value: 'clone',icon: 'clone',},
        {key: 'clone outline',text: 'clone outline',value: 'clone outline',icon: 'clone outline',},
        {key: 'closed captioning',text: 'closed captioning',value: 'closed captioning',icon: 'closed captioning',},
        {key: 'closed captioning outline',text: 'closed captioning outline',value: 'closed captioning outline',icon: 'closed captioning outline',},
        {key: 'cloud',text: 'cloud',value: 'cloud',icon: 'cloud',},
        {key: 'cloud download',text: 'cloud download',value: 'cloud download',icon: 'cloud download',},
        {key: 'cloud upload',text: 'cloud upload',value: 'cloud upload',icon: 'cloud upload',},
        {key: 'cloudscale',text: 'cloudscale',value: 'cloudscale',icon: 'cloudscale',},
        {key: 'cloudsmith',text: 'cloudsmith',value: 'cloudsmith',icon: 'cloudsmith',},
        {key: 'cloudversify',text: 'cloudversify',value: 'cloudversify',icon: 'cloudversify',},
        {key: 'code',text: 'code',value: 'code',icon: 'code',},
        {key: 'code branch',text: 'code branch',value: 'code branch',icon: 'code branch',},
        {key: 'codepen',text: 'codepen',value: 'codepen',icon: 'codepen',},
        {key: 'codiepie',text: 'codiepie',value: 'codiepie',icon: 'codiepie',},
        {key: 'coffee',text: 'coffee',value: 'coffee',icon: 'coffee',},
        {key: 'cog',text: 'cog',value: 'cog',icon: 'cog',},
        {key: 'cogs',text: 'cogs',value: 'cogs',icon: 'cogs',},
        {key: 'columns',text: 'columns',value: 'columns',icon: 'columns',},
        {key: 'comment',text: 'comment',value: 'comment',icon: 'comment',},
        {key: 'comment alternate',text: 'comment alternate',value: 'comment alternate',icon: 'comment alternate',},
        {key: 'comment alternate outline',text: 'comment alternate outline',value: 'comment alternate outline',icon: 'comment alternate outline',},
        {key: 'comment outline',text: 'comment outline',value: 'comment outline',icon: 'comment outline',},
        {key: 'comments',text: 'comments',value: 'comments',icon: 'comments',},
        {key: 'comments outline',text: 'comments outline',value: 'comments outline',icon: 'comments outline',},
        {key: 'compass',text: 'compass',value: 'compass',icon: 'compass',},
        {key: 'compass outline',text: 'compass outline',value: 'compass outline',icon: 'compass outline',},
        {key: 'compress',text: 'compress',value: 'compress',icon: 'compress',},
        {key: 'connectdevelop',text: 'connectdevelop',value: 'connectdevelop',icon: 'connectdevelop',},
        {key: 'contao',text: 'contao',value: 'contao',icon: 'contao',},
        {key: 'copy',text: 'copy',value: 'copy',icon: 'copy',},
        {key: 'copy outline',text: 'copy outline',value: 'copy outline',icon: 'copy outline',},
        {key: 'copyright',text: 'copyright',value: 'copyright',icon: 'copyright',},
        {key: 'copyright outline',text: 'copyright outline',value: 'copyright outline',icon: 'copyright outline',},
        {key: 'cpanel',text: 'cpanel',value: 'cpanel',icon: 'cpanel',},
        {key: 'creative commons',text: 'creative commons',value: 'creative commons',icon: 'creative commons',},
        {key: 'crop',text: 'crop',value: 'crop',icon: 'crop',},
        {key: 'crosshairs',text: 'crosshairs',value: 'crosshairs',icon: 'crosshairs',},
        {key: 'css3',text: 'css3',value: 'css3',icon: 'css3',},
        {key: 'css3 alternate',text: 'css3 alternate',value: 'css3 alternate',icon: 'css3 alternate',},
        {key: 'cube',text: 'cube',value: 'cube',icon: 'cube',},
        {key: 'cubes',text: 'cubes',value: 'cubes',icon: 'cubes',},
        {key: 'cut',text: 'cut',value: 'cut',icon: 'cut',},
        {key: 'cuttlefish',text: 'cuttlefish',value: 'cuttlefish',icon: 'cuttlefish',},
        {key: 'd and d',text: 'd and d',value: 'd and d',icon: 'd and d',},
        {key: 'dashcube',text: 'dashcube',value: 'dashcube',icon: 'dashcube',},
        {key: 'database',text: 'database',value: 'database',icon: 'database',},
        {key: 'deaf',text: 'deaf',value: 'deaf',icon: 'deaf',},
        {key: 'delicious',text: 'delicious',value: 'delicious',icon: 'delicious',},
        {key: 'deploydog',text: 'deploydog',value: 'deploydog',icon: 'deploydog',},
        {key: 'deskpro',text: 'deskpro',value: 'deskpro',icon: 'deskpro',},
        {key: 'desktop',text: 'desktop',value: 'desktop',icon: 'desktop',},
        {key: 'deviantart',text: 'deviantart',value: 'deviantart',icon: 'deviantart',},
        {key: 'digg',text: 'digg',value: 'digg',icon: 'digg',},
        {key: 'digital ocean',text: 'digital ocean',value: 'digital ocean',icon: 'digital ocean',},
        {key: 'discord',text: 'discord',value: 'discord',icon: 'discord',},
        {key: 'discourse',text: 'discourse',value: 'discourse',icon: 'discourse',},
        {key: 'dna',text: 'dna',value: 'dna',icon: 'dna',},
        {key: 'dochub',text: 'dochub',value: 'dochub',icon: 'dochub',},
        {key: 'docker',text: 'docker',value: 'docker',icon: 'docker',},
        {key: 'dollar sign',text: 'dollar sign',value: 'dollar sign',icon: 'dollar sign',},
        {key: 'dolly',text: 'dolly',value: 'dolly',icon: 'dolly',},
        {key: 'dolly flatbed',text: 'dolly flatbed',value: 'dolly flatbed',icon: 'dolly flatbed',},
        {key: 'dot circle',text: 'dot circle',value: 'dot circle',icon: 'dot circle',},
        {key: 'dot circle outline',text: 'dot circle outline',value: 'dot circle outline',icon: 'dot circle outline',},
        {key: 'download',text: 'download',value: 'download',icon: 'download',},
        {key: 'draft2digital',text: 'draft2digital',value: 'draft2digital',icon: 'draft2digital',},
        {key: 'dribbble',text: 'dribbble',value: 'dribbble',icon: 'dribbble',},
        {key: 'dribbble square',text: 'dribbble square',value: 'dribbble square',icon: 'dribbble square',},
        {key: 'dropbox',text: 'dropbox',value: 'dropbox',icon: 'dropbox',},
        {key: 'drupal',text: 'drupal',value: 'drupal',icon: 'drupal',},
        {key: 'dyalog',text: 'dyalog',value: 'dyalog',icon: 'dyalog',},
        {key: 'earlybirds',text: 'earlybirds',value: 'earlybirds',icon: 'earlybirds',},
        {key: 'edge',text: 'edge',value: 'edge',icon: 'edge',},
        {key: 'edit',text: 'edit',value: 'edit',icon: 'edit',},
        {key: 'edit outline',text: 'edit outline',value: 'edit outline',icon: 'edit outline',},
        {key: 'eject',text: 'eject',value: 'eject',icon: 'eject',},
        {key: 'elementor',text: 'elementor',value: 'elementor',icon: 'elementor',},
        {key: 'ellipsis horizontal',text: 'ellipsis horizontal',value: 'ellipsis horizontal',icon: 'ellipsis horizontal',},
        {key: 'ellipsis vertical',text: 'ellipsis vertical',value: 'ellipsis vertical',icon: 'ellipsis vertical',},
        {key: 'ember',text: 'ember',value: 'ember',icon: 'ember',},
        {key: 'empire',text: 'empire',value: 'empire',icon: 'empire',},
        {key: 'envelope',text: 'envelope',value: 'envelope',icon: 'envelope',},
        {key: 'envelope open',text: 'envelope open',value: 'envelope open',icon: 'envelope open',},
        {key: 'envelope open outline',text: 'envelope open outline',value: 'envelope open outline',icon: 'envelope open outline',},
        {key: 'envelope outline',text: 'envelope outline',value: 'envelope outline',icon: 'envelope outline',},
        {key: 'envelope square',text: 'envelope square',value: 'envelope square',icon: 'envelope square',},
        {key: 'envira',text: 'envira',value: 'envira',icon: 'envira',},
        {key: 'eraser',text: 'eraser',value: 'eraser',icon: 'eraser',},
        {key: 'erlang',text: 'erlang',value: 'erlang',icon: 'erlang',},
        {key: 'ethereum',text: 'ethereum',value: 'ethereum',icon: 'ethereum',},
        {key: 'etsy',text: 'etsy',value: 'etsy',icon: 'etsy',},
        {key: 'euro sign',text: 'euro sign',value: 'euro sign',icon: 'euro sign',},
        // {key: 'exchange alternate',text: 'exchange alternate',value: 'exchange alternate',icon: 'exchange alternate',},
        {key: 'exclamation',text: 'exclamation',value: 'exclamation',icon: 'exclamation',},
        {key: 'exclamation circle',text: 'exclamation circle',value: 'exclamation circle',icon: 'exclamation circle',},
        {key: 'exclamation triangle',text: 'exclamation triangle',value: 'exclamation triangle',icon: 'exclamation triangle',},
        {key: 'expand',text: 'expand',value: 'expand',icon: 'expand',},
        {key: 'expand arrows alternate',text: 'expand arrows alternate',value: 'expand arrows alternate',icon: 'expand arrows alternate',},
        {key: 'expeditedssl',text: 'expeditedssl',value: 'expeditedssl',icon: 'expeditedssl',},
        {key: 'external alternate',text: 'external alternate',value: 'external alternate',icon: 'external alternate',},
        {key: 'external square alternate',text: 'external square alternate',value: 'external square alternate',icon: 'external square alternate',},
        {key: 'eye',text: 'eye',value: 'eye',icon: 'eye',},
        {key: 'eye dropper',text: 'eye dropper',value: 'eye dropper',icon: 'eye dropper',},
        {key: 'eye slash',text: 'eye slash',value: 'eye slash',icon: 'eye slash',},
        {key: 'eye slash outline',text: 'eye slash outline',value: 'eye slash outline',icon: 'eye slash outline',},
        {key: 'facebook',text: 'facebook',value: 'facebook',icon: 'facebook',},
        {key: 'facebook f',text: 'facebook f',value: 'facebook f',icon: 'facebook f',},
        {key: 'facebook messenger',text: 'facebook messenger',value: 'facebook messenger',icon: 'facebook messenger',},
        {key: 'facebook square',text: 'facebook square',value: 'facebook square',icon: 'facebook square',},
        {key: 'fast backward',text: 'fast backward',value: 'fast backward',icon: 'fast backward',},
        {key: 'fast forward',text: 'fast forward',value: 'fast forward',icon: 'fast forward',},
        {key: 'fax',text: 'fax',value: 'fax',icon: 'fax',},
        {key: 'female',text: 'female',value: 'female',icon: 'female',},
        {key: 'fighter jet',text: 'fighter jet',value: 'fighter jet',icon: 'fighter jet',},
        {key: 'file',text: 'file',value: 'file',icon: 'file',},
        {key: 'file alternate',text: 'file alternate',value: 'file alternate',icon: 'file alternate',},
        {key: 'file alternate outline',text: 'file alternate outline',value: 'file alternate outline',icon: 'file alternate outline',},
        {key: 'file archive',text: 'file archive',value: 'file archive',icon: 'file archive',},
        {key: 'file archive outline',text: 'file archive outline',value: 'file archive outline',icon: 'file archive outline',},
        {key: 'file audio',text: 'file audio',value: 'file audio',icon: 'file audio',},
        {key: 'file audio outline',text: 'file audio outline',value: 'file audio outline',icon: 'file audio outline',},
        {key: 'file code',text: 'file code',value: 'file code',icon: 'file code',},
        {key: 'file code outline',text: 'file code outline',value: 'file code outline',icon: 'file code outline',},
        {key: 'file excel',text: 'file excel',value: 'file excel',icon: 'file excel',},
        {key: 'file excel outline',text: 'file excel outline',value: 'file excel outline',icon: 'file excel outline',},
        {key: 'file image',text: 'file image',value: 'file image',icon: 'file image',},
        {key: 'file image outline',text: 'file image outline',value: 'file image outline',icon: 'file image outline',},
        {key: 'file outline',text: 'file outline',value: 'file outline',icon: 'file outline',},
        {key: 'file pdf',text: 'file pdf',value: 'file pdf',icon: 'file pdf',},
        {key: 'file pdf outline',text: 'file pdf outline',value: 'file pdf outline',icon: 'file pdf outline',},
        {key: 'file powerpoint',text: 'file powerpoint',value: 'file powerpoint',icon: 'file powerpoint',},
        {key: 'file powerpoint outline',text: 'file powerpoint outline',value: 'file powerpoint outline',icon: 'file powerpoint outline',},
        {key: 'file video',text: 'file video',value: 'file video',icon: 'file video',},
        {key: 'file video outline',text: 'file video outline',value: 'file video outline',icon: 'file video outline',},
        {key: 'file word',text: 'file word',value: 'file word',icon: 'file word',},
        {key: 'file word outline',text: 'file word outline',value: 'file word outline',icon: 'file word outline',},
        {key: 'film',text: 'film',value: 'film',icon: 'film',},
        {key: 'filter',text: 'filter',value: 'filter',icon: 'filter',},
        {key: 'fire',text: 'fire',value: 'fire',icon: 'fire',},
        {key: 'fire extinguisher',text: 'fire extinguisher',value: 'fire extinguisher',icon: 'fire extinguisher',},
        {key: 'firefox',text: 'firefox',value: 'firefox',icon: 'firefox',},
        {key: 'first aid',text: 'first aid',value: 'first aid',icon: 'first aid',},
        {key: 'first order',text: 'first order',value: 'first order',icon: 'first order',},
        {key: 'firstdraft',text: 'firstdraft',value: 'firstdraft',icon: 'firstdraft',},
        {key: 'flag',text: 'flag',value: 'flag',icon: 'flag',},
        {key: 'flag checkered',text: 'flag checkered',value: 'flag checkered',icon: 'flag checkered',},
        {key: 'flag outline',text: 'flag outline',value: 'flag outline',icon: 'flag outline',},
        {key: 'flask',text: 'flask',value: 'flask',icon: 'flask',},
        {key: 'flickr',text: 'flickr',value: 'flickr',icon: 'flickr',},
        {key: 'flipboard',text: 'flipboard',value: 'flipboard',icon: 'flipboard',},
        {key: 'fly',text: 'fly',value: 'fly',icon: 'fly',},
        {key: 'folder',text: 'folder',value: 'folder',icon: 'folder',},
        {key: 'folder open',text: 'folder open',value: 'folder open',icon: 'folder open',},
        {key: 'folder open outline',text: 'folder open outline',value: 'folder open outline',icon: 'folder open outline',},
        {key: 'folder outline',text: 'folder outline',value: 'folder outline',icon: 'folder outline',},
        {key: 'font',text: 'font',value: 'font',icon: 'font',},
        {key: 'font awesome',text: 'font awesome',value: 'font awesome',icon: 'font awesome',},
        {key: 'font awesome alternate',text: 'font awesome alternate',value: 'font awesome alternate',icon: 'font awesome alternate',},
        {key: 'font awesome flag',text: 'font awesome flag',value: 'font awesome flag',icon: 'font awesome flag',},
        {key: 'fonticons',text: 'fonticons',value: 'fonticons',icon: 'fonticons',},
        {key: 'fonticons fi',text: 'fonticons fi',value: 'fonticons fi',icon: 'fonticons fi',},
        {key: 'football ball',text: 'football ball',value: 'football ball',icon: 'football ball',},
        {key: 'fort awesome',text: 'fort awesome',value: 'fort awesome',icon: 'fort awesome',},
        {key: 'fort awesome alternate',text: 'fort awesome alternate',value: 'fort awesome alternate',icon: 'fort awesome alternate',},
        {key: 'forumbee',text: 'forumbee',value: 'forumbee',icon: 'forumbee',},
        {key: 'forward',text: 'forward',value: 'forward',icon: 'forward',},
        {key: 'foursquare',text: 'foursquare',value: 'foursquare',icon: 'foursquare',},
        {key: 'free code camp',text: 'free code camp',value: 'free code camp',icon: 'free code camp',},
        {key: 'freebsd',text: 'freebsd',value: 'freebsd',icon: 'freebsd',},
        {key: 'frown',text: 'frown',value: 'frown',icon: 'frown',},
        {key: 'frown outline',text: 'frown outline',value: 'frown outline',icon: 'frown outline',},
        {key: 'futbol',text: 'futbol',value: 'futbol',icon: 'futbol',},
        {key: 'futbol outline',text: 'futbol outline',value: 'futbol outline',icon: 'futbol outline',},
        {key: 'gamepad',text: 'gamepad',value: 'gamepad',icon: 'gamepad',},
        {key: 'gavel',text: 'gavel',value: 'gavel',icon: 'gavel',},
        {key: 'gem',text: 'gem',value: 'gem',icon: 'gem',},
        {key: 'gem outline',text: 'gem outline',value: 'gem outline',icon: 'gem outline',},
        {key: 'genderless',text: 'genderless',value: 'genderless',icon: 'genderless',},
        {key: 'get pocket',text: 'get pocket',value: 'get pocket',icon: 'get pocket',},
        {key: 'gg',text: 'gg',value: 'gg',icon: 'gg',},
        {key: 'gg circle',text: 'gg circle',value: 'gg circle',icon: 'gg circle',},
        {key: 'gift',text: 'gift',value: 'gift',icon: 'gift',},
        {key: 'git',text: 'git',value: 'git',icon: 'git',},
        {key: 'git square',text: 'git square',value: 'git square',icon: 'git square',},
        {key: 'github',text: 'github',value: 'github',icon: 'github',},
        {key: 'github alternate',text: 'github alternate',value: 'github alternate',icon: 'github alternate',},
        {key: 'github square',text: 'github square',value: 'github square',icon: 'github square',},
        {key: 'gitkraken',text: 'gitkraken',value: 'gitkraken',icon: 'gitkraken',},
        {key: 'gitlab',text: 'gitlab',value: 'gitlab',icon: 'gitlab',},
        {key: 'gitter',text: 'gitter',value: 'gitter',icon: 'gitter',},
        {key: 'glass martini',text: 'glass martini',value: 'glass martini',icon: 'glass martini',},
        {key: 'glide',text: 'glide',value: 'glide',icon: 'glide',},
        {key: 'glide g',text: 'glide g',value: 'glide g',icon: 'glide g',},
        {key: 'globe',text: 'globe',value: 'globe',icon: 'globe',},
        {key: 'gofore',text: 'gofore',value: 'gofore',icon: 'gofore',},
        {key: 'golf ball',text: 'golf ball',value: 'golf ball',icon: 'golf ball',},
        {key: 'goodreads',text: 'goodreads',value: 'goodreads',icon: 'goodreads',},
        {key: 'goodreads g',text: 'goodreads g',value: 'goodreads g',icon: 'goodreads g',},
        {key: 'google',text: 'google',value: 'google',icon: 'google',},
        {key: 'google drive',text: 'google drive',value: 'google drive',icon: 'google drive',},
        {key: 'google play',text: 'google play',value: 'google play',icon: 'google play',},
        {key: 'google plus',text: 'google plus',value: 'google plus',icon: 'google plus',},
        {key: 'google plus g',text: 'google plus g',value: 'google plus g',icon: 'google plus g',},
        {key: 'google plus square',text: 'google plus square',value: 'google plus square',icon: 'google plus square',},
        {key: 'google wallet',text: 'google wallet',value: 'google wallet',icon: 'google wallet',},
        {key: 'graduation cap',text: 'graduation cap',value: 'graduation cap',icon: 'graduation cap',},
        {key: 'gratipay',text: 'gratipay',value: 'gratipay',icon: 'gratipay',},
        {key: 'grav',text: 'grav',value: 'grav',icon: 'grav',},
        {key: 'gripfire',text: 'gripfire',value: 'gripfire',icon: 'gripfire',},
        {key: 'grunt',text: 'grunt',value: 'grunt',icon: 'grunt',},
        {key: 'gulp',text: 'gulp',value: 'gulp',icon: 'gulp',},
        {key: 'h square',text: 'h square',value: 'h square',icon: 'h square',},
        {key: 'hacker news',text: 'hacker news',value: 'hacker news',icon: 'hacker news',},
        {key: 'hacker news square',text: 'hacker news square',value: 'hacker news square',icon: 'hacker news square',},
        {key: 'hand lizard',text: 'hand lizard',value: 'hand lizard',icon: 'hand lizard',},
        {key: 'hand lizard outline',text: 'hand lizard outline',value: 'hand lizard outline',icon: 'hand lizard outline',},
        {key: 'hand paper',text: 'hand paper',value: 'hand paper',icon: 'hand paper',},
        {key: 'hand paper outline',text: 'hand paper outline',value: 'hand paper outline',icon: 'hand paper outline',},
        {key: 'hand peace',text: 'hand peace',value: 'hand peace',icon: 'hand peace',},
        {key: 'hand peace outline',text: 'hand peace outline',value: 'hand peace outline',icon: 'hand peace outline',},
        {key: 'hand point down',text: 'hand point down',value: 'hand point down',icon: 'hand point down',},
        {key: 'hand point down outline',text: 'hand point down outline',value: 'hand point down outline',icon: 'hand point down outline',},
        {key: 'hand point left',text: 'hand point left',value: 'hand point left',icon: 'hand point left',},
        {key: 'hand point left outline',text: 'hand point left outline',value: 'hand point left outline',icon: 'hand point left outline',},
        {key: 'hand point right',text: 'hand point right',value: 'hand point right',icon: 'hand point right',},
        {key: 'hand point right outline',text: 'hand point right outline',value: 'hand point right outline',icon: 'hand point right outline',},
        {key: 'hand point up',text: 'hand point up',value: 'hand point up',icon: 'hand point up',},
        {key: 'hand point up outline',text: 'hand point up outline',value: 'hand point up outline',icon: 'hand point up outline',},
        {key: 'hand pointer',text: 'hand pointer',value: 'hand pointer',icon: 'hand pointer',},
        {key: 'hand pointer outline',text: 'hand pointer outline',value: 'hand pointer outline',icon: 'hand pointer outline',},
        {key: 'hand rock',text: 'hand rock',value: 'hand rock',icon: 'hand rock',},
        {key: 'hand rock outline',text: 'hand rock outline',value: 'hand rock outline',icon: 'hand rock outline',},
        {key: 'hand scissors',text: 'hand scissors',value: 'hand scissors',icon: 'hand scissors',},
        {key: 'hand scissors outline',text: 'hand scissors outline',value: 'hand scissors outline',icon: 'hand scissors outline',},
        {key: 'hand spock',text: 'hand spock',value: 'hand spock',icon: 'hand spock',},
        {key: 'hand spock outline',text: 'hand spock outline',value: 'hand spock outline',icon: 'hand spock outline',},
        {key: 'handshake',text: 'handshake',value: 'handshake',icon: 'handshake',},
        {key: 'handshake outline',text: 'handshake outline',value: 'handshake outline',icon: 'handshake outline',},
        {key: 'hashtag',text: 'hashtag',value: 'hashtag',icon: 'hashtag',},
        {key: 'hdd',text: 'hdd',value: 'hdd',icon: 'hdd',},
        {key: 'hdd outline',text: 'hdd outline',value: 'hdd outline',icon: 'hdd outline',},
        {key: 'heading',text: 'heading',value: 'heading',icon: 'heading',},
        {key: 'headphones',text: 'headphones',value: 'headphones',icon: 'headphones',},
        {key: 'heart',text: 'heart',value: 'heart',icon: 'heart',},
        {key: 'heart outline',text: 'heart outline',value: 'heart outline',icon: 'heart outline',},
        {key: 'heartbeat',text: 'heartbeat',value: 'heartbeat',icon: 'heartbeat',},
        {key: 'hips',text: 'hips',value: 'hips',icon: 'hips',},
        {key: 'hire a helper',text: 'hire a helper',value: 'hire a helper',icon: 'hire a helper',},
        {key: 'history',text: 'history',value: 'history',icon: 'history',},
        {key: 'hockey puck',text: 'hockey puck',value: 'hockey puck',icon: 'hockey puck',},
        {key: 'home',text: 'home',value: 'home',icon: 'home',},
        {key: 'hooli',text: 'hooli',value: 'hooli',icon: 'hooli',},
        {key: 'hospital',text: 'hospital',value: 'hospital',icon: 'hospital',},
        {key: 'hospital outline',text: 'hospital outline',value: 'hospital outline',icon: 'hospital outline',},
        {key: 'hospital symbol',text: 'hospital symbol',value: 'hospital symbol',icon: 'hospital symbol',},
        {key: 'hotjar',text: 'hotjar',value: 'hotjar',icon: 'hotjar',},
        {key: 'hourglass',text: 'hourglass',value: 'hourglass',icon: 'hourglass',},
        {key: 'hourglass end',text: 'hourglass end',value: 'hourglass end',icon: 'hourglass end',},
        {key: 'hourglass half',text: 'hourglass half',value: 'hourglass half',icon: 'hourglass half',},
        {key: 'hourglass outline',text: 'hourglass outline',value: 'hourglass outline',icon: 'hourglass outline',},
        {key: 'hourglass start',text: 'hourglass start',value: 'hourglass start',icon: 'hourglass start',},
        {key: 'houzz',text: 'houzz',value: 'houzz',icon: 'houzz',},
        {key: 'html5',text: 'html5',value: 'html5',icon: 'html5',},
        {key: 'hubspot',text: 'hubspot',value: 'hubspot',icon: 'hubspot',},
        {key: 'i cursor',text: 'i cursor',value: 'i cursor',icon: 'i cursor',},
        {key: 'id badge',text: 'id badge',value: 'id badge',icon: 'id badge',},
        {key: 'id badge outline',text: 'id badge outline',value: 'id badge outline',icon: 'id badge outline',},
        {key: 'id card',text: 'id card',value: 'id card',icon: 'id card',},
        {key: 'id card outline',text: 'id card outline',value: 'id card outline',icon: 'id card outline',},
        {key: 'image',text: 'image',value: 'image',icon: 'image',},
        {key: 'image outline',text: 'image outline',value: 'image outline',icon: 'image outline',},
        {key: 'images',text: 'images',value: 'images',icon: 'images',},
        {key: 'images outline',text: 'images outline',value: 'images outline',icon: 'images outline',},
        {key: 'imdb',text: 'imdb',value: 'imdb',icon: 'imdb',},
        {key: 'inbox',text: 'inbox',value: 'inbox',icon: 'inbox',},
        {key: 'indent',text: 'indent',value: 'indent',icon: 'indent',},
        {key: 'industry',text: 'industry',value: 'industry',icon: 'industry',},
        {key: 'info',text: 'info',value: 'info',icon: 'info',},
        {key: 'info circle',text: 'info circle',value: 'info circle',icon: 'info circle',},
        {key: 'instagram',text: 'instagram',value: 'instagram',icon: 'instagram',},
        {key: 'internet explorer',text: 'internet explorer',value: 'internet explorer',icon: 'internet explorer',},
        {key: 'ioxhost',text: 'ioxhost',value: 'ioxhost',icon: 'ioxhost',},
        {key: 'italic',text: 'italic',value: 'italic',icon: 'italic',},
        {key: 'itunes',text: 'itunes',value: 'itunes',icon: 'itunes',},
        {key: 'itunes note',text: 'itunes note',value: 'itunes note',icon: 'itunes note',},
        {key: 'jenkins',text: 'jenkins',value: 'jenkins',icon: 'jenkins',},
        {key: 'joget',text: 'joget',value: 'joget',icon: 'joget',},
        {key: 'joomla',text: 'joomla',value: 'joomla',icon: 'joomla',},
        {key: 'js',text: 'js',value: 'js',icon: 'js',},
        {key: 'js square',text: 'js square',value: 'js square',icon: 'js square',},
        {key: 'jsfiddle',text: 'jsfiddle',value: 'jsfiddle',icon: 'jsfiddle',},
        {key: 'key',text: 'key',value: 'key',icon: 'key',},
        {key: 'keyboard',text: 'keyboard',value: 'keyboard',icon: 'keyboard',},
        {key: 'keyboard outline',text: 'keyboard outline',value: 'keyboard outline',icon: 'keyboard outline',},
        {key: 'keycdn',text: 'keycdn',value: 'keycdn',icon: 'keycdn',},
        {key: 'kickstarter',text: 'kickstarter',value: 'kickstarter',icon: 'kickstarter',},
        {key: 'kickstarter k',text: 'kickstarter k',value: 'kickstarter k',icon: 'kickstarter k',},
        {key: 'korvue',text: 'korvue',value: 'korvue',icon: 'korvue',},
        {key: 'language',text: 'language',value: 'language',icon: 'language',},
        {key: 'laptop',text: 'laptop',value: 'laptop',icon: 'laptop',},
        {key: 'laravel',text: 'laravel',value: 'laravel',icon: 'laravel',},
        {key: 'lastfm',text: 'lastfm',value: 'lastfm',icon: 'lastfm',},
        {key: 'lastfm square',text: 'lastfm square',value: 'lastfm square',icon: 'lastfm square',},
        {key: 'leaf',text: 'leaf',value: 'leaf',icon: 'leaf',},
        {key: 'leanpub',text: 'leanpub',value: 'leanpub',icon: 'leanpub',},
        {key: 'lemon',text: 'lemon',value: 'lemon',icon: 'lemon',},
        {key: 'lemon outline',text: 'lemon outline',value: 'lemon outline',icon: 'lemon outline',},
        {key: 'less',text: 'less',value: 'less',icon: 'less',},
        {key: 'level down alternate',text: 'level down alternate',value: 'level down alternate',icon: 'level down alternate',},
        {key: 'level up alternate',text: 'level up alternate',value: 'level up alternate',icon: 'level up alternate',},
        {key: 'life ring',text: 'life ring',value: 'life ring',icon: 'life ring',},
        {key: 'life ring outline',text: 'life ring outline',value: 'life ring outline',icon: 'life ring outline',},
        {key: 'lightbulb',text: 'lightbulb',value: 'lightbulb',icon: 'lightbulb',},
        {key: 'lightbulb outline',text: 'lightbulb outline',value: 'lightbulb outline',icon: 'lightbulb outline',},
        {key: 'linechat',text: 'linechat',value: 'linechat',icon: 'linechat',},
        {key: 'linkedin',text: 'linkedin',value: 'linkedin',icon: 'linkedin',},
        // {key: 'linkedin in',text: 'linkedin in',value: 'linkedin in',icon: 'linkedin in',},
        {key: 'linkify',text: 'linkify',value: 'linkify',icon: 'linkify',},
        {key: 'linode',text: 'linode',value: 'linode',icon: 'linode',},
        {key: 'linux',text: 'linux',value: 'linux',icon: 'linux',},
        {key: 'lira sign',text: 'lira sign',value: 'lira sign',icon: 'lira sign',},
        {key: 'list',text: 'list',value: 'list',icon: 'list',},
        {key: 'list alternate',text: 'list alternate',value: 'list alternate',icon: 'list alternate',},
        {key: 'list alternate outline',text: 'list alternate outline',value: 'list alternate outline',icon: 'list alternate outline',},
        {key: 'list ol',text: 'list ol',value: 'list ol',icon: 'list ol',},
        {key: 'list ul',text: 'list ul',value: 'list ul',icon: 'list ul',},
        {key: 'location arrow',text: 'location arrow',value: 'location arrow',icon: 'location arrow',},
        {key: 'lock',text: 'lock',value: 'lock',icon: 'lock',},
        {key: 'lock open',text: 'lock open',value: 'lock open',icon: 'lock open',},
        {key: 'long arrow alternate down',text: 'long arrow alternate down',value: 'long arrow alternate down',icon: 'long arrow alternate down',},
        {key: 'long arrow alternate left',text: 'long arrow alternate left',value: 'long arrow alternate left',icon: 'long arrow alternate left',},
        {key: 'long arrow alternate right',text: 'long arrow alternate right',value: 'long arrow alternate right',icon: 'long arrow alternate right',},
        {key: 'long arrow alternate up',text: 'long arrow alternate up',value: 'long arrow alternate up',icon: 'long arrow alternate up',},
        {key: 'low vision',text: 'low vision',value: 'low vision',icon: 'low vision',},
        {key: 'lyft',text: 'lyft',value: 'lyft',icon: 'lyft',},
        {key: 'magento',text: 'magento',value: 'magento',icon: 'magento',},
        {key: 'magic',text: 'magic',value: 'magic',icon: 'magic',},
        {key: 'magnet',text: 'magnet',value: 'magnet',icon: 'magnet',},
        {key: 'male',text: 'male',value: 'male',icon: 'male',},
        {key: 'map',text: 'map',value: 'map',icon: 'map',},
        {key: 'map marker',text: 'map marker',value: 'map marker',icon: 'map marker',},
        {key: 'map marker alternate',text: 'map marker alternate',value: 'map marker alternate',icon: 'map marker alternate',},
        {key: 'map outline',text: 'map outline',value: 'map outline',icon: 'map outline',},
        {key: 'map pin',text: 'map pin',value: 'map pin',icon: 'map pin',},
        {key: 'map signs',text: 'map signs',value: 'map signs',icon: 'map signs',},
        {key: 'mars',text: 'mars',value: 'mars',icon: 'mars',},
        {key: 'mars double',text: 'mars double',value: 'mars double',icon: 'mars double',},
        {key: 'mars stroke',text: 'mars stroke',value: 'mars stroke',icon: 'mars stroke',},
        {key: 'mars stroke horizontal',text: 'mars stroke horizontal',value: 'mars stroke horizontal',icon: 'mars stroke horizontal',},
        {key: 'mars stroke vertical',text: 'mars stroke vertical',value: 'mars stroke vertical',icon: 'mars stroke vertical',},
        {key: 'maxcdn',text: 'maxcdn',value: 'maxcdn',icon: 'maxcdn',},
        {key: 'medapps',text: 'medapps',value: 'medapps',icon: 'medapps',},
        {key: 'medium',text: 'medium',value: 'medium',icon: 'medium',},
        {key: 'medium m',text: 'medium m',value: 'medium m',icon: 'medium m',},
        {key: 'medkit',text: 'medkit',value: 'medkit',icon: 'medkit',},
        {key: 'medrt',text: 'medrt',value: 'medrt',icon: 'medrt',},
        {key: 'meetup',text: 'meetup',value: 'meetup',icon: 'meetup',},
        {key: 'meh',text: 'meh',value: 'meh',icon: 'meh',},
        {key: 'meh outline',text: 'meh outline',value: 'meh outline',icon: 'meh outline',},
        {key: 'mercury',text: 'mercury',value: 'mercury',icon: 'mercury',},
        {key: 'microchip',text: 'microchip',value: 'microchip',icon: 'microchip',},
        {key: 'microphone',text: 'microphone',value: 'microphone',icon: 'microphone',},
        {key: 'microphone slash',text: 'microphone slash',value: 'microphone slash',icon: 'microphone slash',},
        {key: 'microsoft',text: 'microsoft',value: 'microsoft',icon: 'microsoft',},
        {key: 'minus',text: 'minus',value: 'minus',icon: 'minus',},
        {key: 'minus circle',text: 'minus circle',value: 'minus circle',icon: 'minus circle',},
        {key: 'minus square',text: 'minus square',value: 'minus square',icon: 'minus square',},
        {key: 'minus square outline',text: 'minus square outline',value: 'minus square outline',icon: 'minus square outline',},
        {key: 'mix',text: 'mix',value: 'mix',icon: 'mix',},
        {key: 'mixcloud',text: 'mixcloud',value: 'mixcloud',icon: 'mixcloud',},
        {key: 'mizuni',text: 'mizuni',value: 'mizuni',icon: 'mizuni',},
        {key: 'mobile',text: 'mobile',value: 'mobile',icon: 'mobile',},
        {key: 'mobile alternate',text: 'mobile alternate',value: 'mobile alternate',icon: 'mobile alternate',},
        {key: 'modx',text: 'modx',value: 'modx',icon: 'modx',},
        {key: 'monero',text: 'monero',value: 'monero',icon: 'monero',},
        {key: 'money bill alternate',text: 'money bill alternate',value: 'money bill alternate',icon: 'money bill alternate',},
        {key: 'money bill alternate outline',text: 'money bill alternate outline',value: 'money bill alternate outline',icon: 'money bill alternate outline',},
        {key: 'moon',text: 'moon',value: 'moon',icon: 'moon',},
        {key: 'moon outline',text: 'moon outline',value: 'moon outline',icon: 'moon outline',},
        {key: 'motorcycle',text: 'motorcycle',value: 'motorcycle',icon: 'motorcycle',},
        {key: 'mouse pointer',text: 'mouse pointer',value: 'mouse pointer',icon: 'mouse pointer',},
        {key: 'music',text: 'music',value: 'music',icon: 'music',},
        {key: 'napster',text: 'napster',value: 'napster',icon: 'napster',},
        {key: 'neuter',text: 'neuter',value: 'neuter',icon: 'neuter',},
        {key: 'newspaper',text: 'newspaper',value: 'newspaper',icon: 'newspaper',},
        {key: 'newspaper outline',text: 'newspaper outline',value: 'newspaper outline',icon: 'newspaper outline',},
        {key: 'nintendo switch',text: 'nintendo switch',value: 'nintendo switch',icon: 'nintendo switch',},
        {key: 'node',text: 'node',value: 'node',icon: 'node',},
        {key: 'node js',text: 'node js',value: 'node js',icon: 'node js',},
        {key: 'npm',text: 'npm',value: 'npm',icon: 'npm',},
        {key: 'ns8',text: 'ns8',value: 'ns8',icon: 'ns8',},
        {key: 'nutritionix',text: 'nutritionix',value: 'nutritionix',icon: 'nutritionix',},
        {key: 'object group',text: 'object group',value: 'object group',icon: 'object group',},
        {key: 'object group outline',text: 'object group outline',value: 'object group outline',icon: 'object group outline',},
        {key: 'object ungroup',text: 'object ungroup',value: 'object ungroup',icon: 'object ungroup',},
        {key: 'object ungroup outline',text: 'object ungroup outline',value: 'object ungroup outline',icon: 'object ungroup outline',},
        {key: 'odnoklassniki',text: 'odnoklassniki',value: 'odnoklassniki',icon: 'odnoklassniki',},
        {key: 'odnoklassniki square',text: 'odnoklassniki square',value: 'odnoklassniki square',icon: 'odnoklassniki square',},
        {key: 'opencart',text: 'opencart',value: 'opencart',icon: 'opencart',},
        {key: 'openid',text: 'openid',value: 'openid',icon: 'openid',},
        {key: 'opera',text: 'opera',value: 'opera',icon: 'opera',},
        {key: 'optin monster',text: 'optin monster',value: 'optin monster',icon: 'optin monster',},
        {key: 'osi',text: 'osi',value: 'osi',icon: 'osi',},
        {key: 'outdent',text: 'outdent',value: 'outdent',icon: 'outdent',},
        {key: 'page4',text: 'page4',value: 'page4',icon: 'page4',},
        {key: 'pagelines',text: 'pagelines',value: 'pagelines',icon: 'pagelines',},
        {key: 'paint brush',text: 'paint brush',value: 'paint brush',icon: 'paint brush',},
        {key: 'palfed',text: 'palfed',value: 'palfed',icon: 'palfed',},
        {key: 'pallet',text: 'pallet',value: 'pallet',icon: 'pallet',},
        {key: 'paper plane',text: 'paper plane',value: 'paper plane',icon: 'paper plane',},
        {key: 'paper plane outline',text: 'paper plane outline',value: 'paper plane outline',icon: 'paper plane outline',},
        {key: 'paperclip',text: 'paperclip',value: 'paperclip',icon: 'paperclip',},
        {key: 'paragraph',text: 'paragraph',value: 'paragraph',icon: 'paragraph',},
        {key: 'paste',text: 'paste',value: 'paste',icon: 'paste',},
        {key: 'patreon',text: 'patreon',value: 'patreon',icon: 'patreon',},
        {key: 'pause',text: 'pause',value: 'pause',icon: 'pause',},
        {key: 'pause circle',text: 'pause circle',value: 'pause circle',icon: 'pause circle',},
        {key: 'pause circle outline',text: 'pause circle outline',value: 'pause circle outline',icon: 'pause circle outline',},
        {key: 'paw',text: 'paw',value: 'paw',icon: 'paw',},
        {key: 'paypal',text: 'paypal',value: 'paypal',icon: 'paypal',},
        {key: 'pen square',text: 'pen square',value: 'pen square',icon: 'pen square',},
        {key: 'pencil alternate',text: 'pencil alternate',value: 'pencil alternate',icon: 'pencil alternate',},
        {key: 'percent',text: 'percent',value: 'percent',icon: 'percent',},
        {key: 'periscope',text: 'periscope',value: 'periscope',icon: 'periscope',},
        {key: 'phabricator',text: 'phabricator',value: 'phabricator',icon: 'phabricator',},
        {key: 'phoenix framework',text: 'phoenix framework',value: 'phoenix framework',icon: 'phoenix framework',},
        {key: 'phone',text: 'phone',value: 'phone',icon: 'phone',},
        {key: 'phone square',text: 'phone square',value: 'phone square',icon: 'phone square',},
        {key: 'phone volume',text: 'phone volume',value: 'phone volume',icon: 'phone volume',},
        {key: 'php',text: 'php',value: 'php',icon: 'php',},
        {key: 'pied piper',text: 'pied piper',value: 'pied piper',icon: 'pied piper',},
        {key: 'pied piper alternate',text: 'pied piper alternate',value: 'pied piper alternate',icon: 'pied piper alternate',},
        {key: 'pied piper pp',text: 'pied piper pp',value: 'pied piper pp',icon: 'pied piper pp',},
        {key: 'pills',text: 'pills',value: 'pills',icon: 'pills',},
        {key: 'pinterest',text: 'pinterest',value: 'pinterest',icon: 'pinterest',},
        {key: 'pinterest p',text: 'pinterest p',value: 'pinterest p',icon: 'pinterest p',},
        {key: 'pinterest square',text: 'pinterest square',value: 'pinterest square',icon: 'pinterest square',},
        {key: 'plane',text: 'plane',value: 'plane',icon: 'plane',},
        {key: 'play',text: 'play',value: 'play',icon: 'play',},
        {key: 'play circle',text: 'play circle',value: 'play circle',icon: 'play circle',},
        {key: 'play circle outline',text: 'play circle outline',value: 'play circle outline',icon: 'play circle outline',},
        {key: 'playstation',text: 'playstation',value: 'playstation',icon: 'playstation',},
        {key: 'plug',text: 'plug',value: 'plug',icon: 'plug',},
        {key: 'plus',text: 'plus',value: 'plus',icon: 'plus',},
        {key: 'plus circle',text: 'plus circle',value: 'plus circle',icon: 'plus circle',},
        {key: 'plus square',text: 'plus square',value: 'plus square',icon: 'plus square',},
        {key: 'plus square outline',text: 'plus square outline',value: 'plus square outline',icon: 'plus square outline',},
        {key: 'podcast',text: 'podcast',value: 'podcast',icon: 'podcast',},
        {key: 'pound sign',text: 'pound sign',value: 'pound sign',icon: 'pound sign',},
        {key: 'power off',text: 'power off',value: 'power off',icon: 'power off',},
        {key: 'print',text: 'print',value: 'print',icon: 'print',},
        {key: 'product hunt',text: 'product hunt',value: 'product hunt',icon: 'product hunt',},
        {key: 'pushed',text: 'pushed',value: 'pushed',icon: 'pushed',},
        {key: 'puzzle piece',text: 'puzzle piece',value: 'puzzle piece',icon: 'puzzle piece',},
        {key: 'python',text: 'python',value: 'python',icon: 'python',},
        {key: 'qq',text: 'qq',value: 'qq',icon: 'qq',},
        {key: 'qrcode',text: 'qrcode',value: 'qrcode',icon: 'qrcode',},
        {key: 'question',text: 'question',value: 'question',icon: 'question',},
        {key: 'question circle',text: 'question circle',value: 'question circle',icon: 'question circle',},
        {key: 'question circle outline',text: 'question circle outline',value: 'question circle outline',icon: 'question circle outline',},
        {key: 'quidditch',text: 'quidditch',value: 'quidditch',icon: 'quidditch',},
        {key: 'quinscape',text: 'quinscape',value: 'quinscape',icon: 'quinscape',},
        {key: 'quora',text: 'quora',value: 'quora',icon: 'quora',},
        {key: 'quote left',text: 'quote left',value: 'quote left',icon: 'quote left',},
        {key: 'quote right',text: 'quote right',value: 'quote right',icon: 'quote right',},
        {key: 'random',text: 'random',value: 'random',icon: 'random',},
        {key: 'ravelry',text: 'ravelry',value: 'ravelry',icon: 'ravelry',},
        {key: 'react',text: 'react',value: 'react',icon: 'react',},
        {key: 'rebel',text: 'rebel',value: 'rebel',icon: 'rebel',},
        {key: 'recycle',text: 'recycle',value: 'recycle',icon: 'recycle',},
        {key: 'reddit',text: 'reddit',value: 'reddit',icon: 'reddit',},
        {key: 'reddit alien',text: 'reddit alien',value: 'reddit alien',icon: 'reddit alien',},
        {key: 'reddit square',text: 'reddit square',value: 'reddit square',icon: 'reddit square',},
        {key: 'redo',text: 'redo',value: 'redo',icon: 'redo',},
        {key: 'redo alternate',text: 'redo alternate',value: 'redo alternate',icon: 'redo alternate',},
        {key: 'redriver',text: 'redriver',value: 'redriver',icon: 'redriver',},
        {key: 'registered',text: 'registered',value: 'registered',icon: 'registered',},
        {key: 'registered outline',text: 'registered outline',value: 'registered outline',icon: 'registered outline',},
        {key: 'rendact',text: 'rendact',value: 'rendact',icon: 'rendact',},
        {key: 'renren',text: 'renren',value: 'renren',icon: 'renren',},
        {key: 'reply',text: 'reply',value: 'reply',icon: 'reply',},
        {key: 'reply all',text: 'reply all',value: 'reply all',icon: 'reply all',},
        {key: 'replyd',text: 'replyd',value: 'replyd',icon: 'replyd',},
        {key: 'resolving',text: 'resolving',value: 'resolving',icon: 'resolving',},
        {key: 'retweet',text: 'retweet',value: 'retweet',icon: 'retweet',},
        {key: 'road',text: 'road',value: 'road',icon: 'road',},
        {key: 'rocket',text: 'rocket',value: 'rocket',icon: 'rocket',},
        {key: 'rocketchat',text: 'rocketchat',value: 'rocketchat',icon: 'rocketchat',},
        {key: 'rockrms',text: 'rockrms',value: 'rockrms',icon: 'rockrms',},
        {key: 'rss',text: 'rss',value: 'rss',icon: 'rss',},
        {key: 'rss square',text: 'rss square',value: 'rss square',icon: 'rss square',},
        {key: 'ruble sign',text: 'ruble sign',value: 'ruble sign',icon: 'ruble sign',},
        {key: 'rupee sign',text: 'rupee sign',value: 'rupee sign',icon: 'rupee sign',},
        {key: 'safari',text: 'safari',value: 'safari',icon: 'safari',},
        {key: 'sass',text: 'sass',value: 'sass',icon: 'sass',},
        {key: 'save',text: 'save',value: 'save',icon: 'save',},
        {key: 'save outline',text: 'save outline',value: 'save outline',icon: 'save outline',},
        {key: 'schlix',text: 'schlix',value: 'schlix',icon: 'schlix',},
        {key: 'scribd',text: 'scribd',value: 'scribd',icon: 'scribd',},
        {key: 'search',text: 'search',value: 'search',icon: 'search',},
        {key: 'search minus',text: 'search minus',value: 'search minus',icon: 'search minus',},
        {key: 'search plus',text: 'search plus',value: 'search plus',icon: 'search plus',},
        {key: 'searchengin',text: 'searchengin',value: 'searchengin',icon: 'searchengin',},
        {key: 'sellcast',text: 'sellcast',value: 'sellcast',icon: 'sellcast',},
        {key: 'sellsy',text: 'sellsy',value: 'sellsy',icon: 'sellsy',},
        {key: 'server',text: 'server',value: 'server',icon: 'server',},
        {key: 'servicestack',text: 'servicestack',value: 'servicestack',icon: 'servicestack',},
        {key: 'share',text: 'share',value: 'share',icon: 'share',},
        {key: 'share alternate',text: 'share alternate',value: 'share alternate',icon: 'share alternate',},
        {key: 'share alternate square',text: 'share alternate square',value: 'share alternate square',icon: 'share alternate square',},
        {key: 'share square',text: 'share square',value: 'share square',icon: 'share square',},
        {key: 'share square outline',text: 'share square outline',value: 'share square outline',icon: 'share square outline',},
        {key: 'shekel sign',text: 'shekel sign',value: 'shekel sign',icon: 'shekel sign',},
        {key: 'shield alternate',text: 'shield alternate',value: 'shield alternate',icon: 'shield alternate',},
        {key: 'ship',text: 'ship',value: 'ship',icon: 'ship',},
        {key: 'shipping fast',text: 'shipping fast',value: 'shipping fast',icon: 'shipping fast',},
        {key: 'shirtsinbulk',text: 'shirtsinbulk',value: 'shirtsinbulk',icon: 'shirtsinbulk',},
        {key: 'shopping bag',text: 'shopping bag',value: 'shopping bag',icon: 'shopping bag',},
        {key: 'shopping basket',text: 'shopping basket',value: 'shopping basket',icon: 'shopping basket',},
        {key: 'shopping cart',text: 'shopping cart',value: 'shopping cart',icon: 'shopping cart',},
        {key: 'shower',text: 'shower',value: 'shower',icon: 'shower',},
        {key: 'sign in alternate',text: 'sign in alternate',value: 'sign in alternate',icon: 'sign in alternate',},
        {key: 'sign language',text: 'sign language',value: 'sign language',icon: 'sign language',},
        {key: 'sign out alternate',text: 'sign out alternate',value: 'sign out alternate',icon: 'sign out alternate',},
        {key: 'signal',text: 'signal',value: 'signal',icon: 'signal',},
        {key: 'simplybuilt',text: 'simplybuilt',value: 'simplybuilt',icon: 'simplybuilt',},
        {key: 'sistrix',text: 'sistrix',value: 'sistrix',icon: 'sistrix',},
        {key: 'sitemap',text: 'sitemap',value: 'sitemap',icon: 'sitemap',},
        {key: 'skyatlas',text: 'skyatlas',value: 'skyatlas',icon: 'skyatlas',},
        {key: 'skype',text: 'skype',value: 'skype',icon: 'skype',},
        {key: 'slack',text: 'slack',value: 'slack',icon: 'slack',},
        {key: 'slack hash',text: 'slack hash',value: 'slack hash',icon: 'slack hash',},
        {key: 'sliders horizontal',text: 'sliders horizontal',value: 'sliders horizontal',icon: 'sliders horizontal',},
        {key: 'slideshare',text: 'slideshare',value: 'slideshare',icon: 'slideshare',},
        {key: 'smile',text: 'smile',value: 'smile',icon: 'smile',},
        {key: 'smile outline',text: 'smile outline',value: 'smile outline',icon: 'smile outline',},
        {key: 'snapchat',text: 'snapchat',value: 'snapchat',icon: 'snapchat',},
        {key: 'snapchat ghost',text: 'snapchat ghost',value: 'snapchat ghost',icon: 'snapchat ghost',},
        {key: 'snapchat square',text: 'snapchat square',value: 'snapchat square',icon: 'snapchat square',},
        {key: 'snowflake',text: 'snowflake',value: 'snowflake',icon: 'snowflake',},
        {key: 'snowflake outline',text: 'snowflake outline',value: 'snowflake outline',icon: 'snowflake outline',},
        {key: 'sort',text: 'sort',value: 'sort',icon: 'sort',},
        {key: 'sort alphabet down',text: 'sort alphabet down',value: 'sort alphabet down',icon: 'sort alphabet down',},
        {key: 'sort alphabet up',text: 'sort alphabet up',value: 'sort alphabet up',icon: 'sort alphabet up',},
        {key: 'sort amount down',text: 'sort amount down',value: 'sort amount down',icon: 'sort amount down',},
        {key: 'sort amount up',text: 'sort amount up',value: 'sort amount up',icon: 'sort amount up',},
        {key: 'sort down',text: 'sort down',value: 'sort down',icon: 'sort down',},
        {key: 'sort numeric down',text: 'sort numeric down',value: 'sort numeric down',icon: 'sort numeric down',},
        {key: 'sort numeric up',text: 'sort numeric up',value: 'sort numeric up',icon: 'sort numeric up',},
        {key: 'sort up',text: 'sort up',value: 'sort up',icon: 'sort up',},
        {key: 'soundcloud',text: 'soundcloud',value: 'soundcloud',icon: 'soundcloud',},
        {key: 'space shuttle',text: 'space shuttle',value: 'space shuttle',icon: 'space shuttle',},
        {key: 'speakap',text: 'speakap',value: 'speakap',icon: 'speakap',},
        {key: 'spinner',text: 'spinner',value: 'spinner',icon: 'spinner',},
        {key: 'spotify',text: 'spotify',value: 'spotify',icon: 'spotify',},
        {key: 'square',text: 'square',value: 'square',icon: 'square',},
        {key: 'square full',text: 'square full',value: 'square full',icon: 'square full',},
        {key: 'square outline',text: 'square outline',value: 'square outline',icon: 'square outline',},
        {key: 'stack exchange',text: 'stack exchange',value: 'stack exchange',icon: 'stack exchange',},
        {key: 'stack overflow',text: 'stack overflow',value: 'stack overflow',icon: 'stack overflow',},
        {key: 'star',text: 'star',value: 'star',icon: 'star',},
        {key: 'star half',text: 'star half',value: 'star half',icon: 'star half',},
        {key: 'star half outline',text: 'star half outline',value: 'star half outline',icon: 'star half outline',},
        {key: 'star outline',text: 'star outline',value: 'star outline',icon: 'star outline',},
        {key: 'staylinked',text: 'staylinked',value: 'staylinked',icon: 'staylinked',},
        {key: 'steam',text: 'steam',value: 'steam',icon: 'steam',},
        {key: 'steam square',text: 'steam square',value: 'steam square',icon: 'steam square',},
        {key: 'steam symbol',text: 'steam symbol',value: 'steam symbol',icon: 'steam symbol',},
        {key: 'step backward',text: 'step backward',value: 'step backward',icon: 'step backward',},
        {key: 'step forward',text: 'step forward',value: 'step forward',icon: 'step forward',},
        {key: 'stethoscope',text: 'stethoscope',value: 'stethoscope',icon: 'stethoscope',},
        {key: 'sticker mule',text: 'sticker mule',value: 'sticker mule',icon: 'sticker mule',},
        {key: 'sticky note',text: 'sticky note',value: 'sticky note',icon: 'sticky note',},
        {key: 'sticky note outline',text: 'sticky note outline',value: 'sticky note outline',icon: 'sticky note outline',},
        {key: 'stop',text: 'stop',value: 'stop',icon: 'stop',},
        {key: 'stop circle',text: 'stop circle',value: 'stop circle',icon: 'stop circle',},
        {key: 'stop circle outline',text: 'stop circle outline',value: 'stop circle outline',icon: 'stop circle outline',},
        {key: 'stopwatch',text: 'stopwatch',value: 'stopwatch',icon: 'stopwatch',},
        {key: 'strava',text: 'strava',value: 'strava',icon: 'strava',},
        {key: 'street view',text: 'street view',value: 'street view',icon: 'street view',},
        {key: 'strikethrough',text: 'strikethrough',value: 'strikethrough',icon: 'strikethrough',},
        {key: 'stripe',text: 'stripe',value: 'stripe',icon: 'stripe',},
        {key: 'stripe s',text: 'stripe s',value: 'stripe s',icon: 'stripe s',},
        {key: 'studiovinari',text: 'studiovinari',value: 'studiovinari',icon: 'studiovinari',},
        {key: 'stumbleupon',text: 'stumbleupon',value: 'stumbleupon',icon: 'stumbleupon',},
        {key: 'stumbleupon circle',text: 'stumbleupon circle',value: 'stumbleupon circle',icon: 'stumbleupon circle',},
        {key: 'subscript',text: 'subscript',value: 'subscript',icon: 'subscript',},
        {key: 'subway',text: 'subway',value: 'subway',icon: 'subway',},
        {key: 'suitcase',text: 'suitcase',value: 'suitcase',icon: 'suitcase',},
        {key: 'sun',text: 'sun',value: 'sun',icon: 'sun',},
        {key: 'sun outline',text: 'sun outline',value: 'sun outline',icon: 'sun outline',},
        {key: 'superpowers',text: 'superpowers',value: 'superpowers',icon: 'superpowers',},
        {key: 'superscript',text: 'superscript',value: 'superscript',icon: 'superscript',},
        {key: 'supple',text: 'supple',value: 'supple',icon: 'supple',},
        {key: 'sync',text: 'sync',value: 'sync',icon: 'sync',},
        {key: 'sync alternate',text: 'sync alternate',value: 'sync alternate',icon: 'sync alternate',},
        {key: 'syringe',text: 'syringe',value: 'syringe',icon: 'syringe',},
        {key: 'table',text: 'table',value: 'table',icon: 'table',},
        {key: 'table tennis',text: 'table tennis',value: 'table tennis',icon: 'table tennis',},
        {key: 'tablet',text: 'tablet',value: 'tablet',icon: 'tablet',},
        {key: 'tablet alternate',text: 'tablet alternate',value: 'tablet alternate',icon: 'tablet alternate',},
        {key: 'tachometer alternate',text: 'tachometer alternate',value: 'tachometer alternate',icon: 'tachometer alternate',},
        {key: 'tag',text: 'tag',value: 'tag',icon: 'tag',},
        {key: 'tags',text: 'tags',value: 'tags',icon: 'tags',},
        {key: 'tasks',text: 'tasks',value: 'tasks',icon: 'tasks',},
        {key: 'taxi',text: 'taxi',value: 'taxi',icon: 'taxi',},
        {key: 'telegram',text: 'telegram',value: 'telegram',icon: 'telegram',},
        {key: 'telegram plane',text: 'telegram plane',value: 'telegram plane',icon: 'telegram plane',},
        {key: 'tencent weibo',text: 'tencent weibo',value: 'tencent weibo',icon: 'tencent weibo',},
        {key: 'terminal',text: 'terminal',value: 'terminal',icon: 'terminal',},
        {key: 'text height',text: 'text height',value: 'text height',icon: 'text height',},
        {key: 'text width',text: 'text width',value: 'text width',icon: 'text width',},
        {key: 'th',text: 'th',value: 'th',icon: 'th',},
        {key: 'th large',text: 'th large',value: 'th large',icon: 'th large',},
        {key: 'th list',text: 'th list',value: 'th list',icon: 'th list',},
        {key: 'themeisle',text: 'themeisle',value: 'themeisle',icon: 'themeisle',},
        {key: 'thermometer',text: 'thermometer',value: 'thermometer',icon: 'thermometer',},
        {key: 'thermometer empty',text: 'thermometer empty',value: 'thermometer empty',icon: 'thermometer empty',},
        {key: 'thermometer full',text: 'thermometer full',value: 'thermometer full',icon: 'thermometer full',},
        {key: 'thermometer half',text: 'thermometer half',value: 'thermometer half',icon: 'thermometer half',},
        {key: 'thermometer quarter',text: 'thermometer quarter',value: 'thermometer quarter',icon: 'thermometer quarter',},
        {key: 'thermometer three quarters',text: 'thermometer three quarters',value: 'thermometer three quarters',icon: 'thermometer three quarters',},
        {key: 'thumbs down',text: 'thumbs down',value: 'thumbs down',icon: 'thumbs down',},
        {key: 'thumbs down outline',text: 'thumbs down outline',value: 'thumbs down outline',icon: 'thumbs down outline',},
        {key: 'thumbs up',text: 'thumbs up',value: 'thumbs up',icon: 'thumbs up',},
        {key: 'thumbs up outline',text: 'thumbs up outline',value: 'thumbs up outline',icon: 'thumbs up outline',},
        {key: 'thumbtack',text: 'thumbtack',value: 'thumbtack',icon: 'thumbtack',},
        {key: 'ticket alternate',text: 'ticket alternate',value: 'ticket alternate',icon: 'ticket alternate',},
        {key: 'times',text: 'times',value: 'times',icon: 'times',},
        {key: 'times circle',text: 'times circle',value: 'times circle',icon: 'times circle',},
        {key: 'times circle outline',text: 'times circle outline',value: 'times circle outline',icon: 'times circle outline',},
        {key: 'tint',text: 'tint',value: 'tint',icon: 'tint',},
        {key: 'toggle off',text: 'toggle off',value: 'toggle off',icon: 'toggle off',},
        {key: 'toggle on',text: 'toggle on',value: 'toggle on',icon: 'toggle on',},
        {key: 'trademark',text: 'trademark',value: 'trademark',icon: 'trademark',},
        {key: 'train',text: 'train',value: 'train',icon: 'train',},
        {key: 'transgender',text: 'transgender',value: 'transgender',icon: 'transgender',},
        {key: 'transgender alternate',text: 'transgender alternate',value: 'transgender alternate',icon: 'transgender alternate',},
        {key: 'trash',text: 'trash',value: 'trash',icon: 'trash',},
        {key: 'trash alternate',text: 'trash alternate',value: 'trash alternate',icon: 'trash alternate',},
        {key: 'trash alternate outline',text: 'trash alternate outline',value: 'trash alternate outline',icon: 'trash alternate outline',},
        {key: 'tree',text: 'tree',value: 'tree',icon: 'tree',},
        {key: 'trello',text: 'trello',value: 'trello',icon: 'trello',},
        {key: 'tripadvisor',text: 'tripadvisor',value: 'tripadvisor',icon: 'tripadvisor',},
        {key: 'trophy',text: 'trophy',value: 'trophy',icon: 'trophy',},
        {key: 'truck',text: 'truck',value: 'truck',icon: 'truck',},
        {key: 'tty',text: 'tty',value: 'tty',icon: 'tty',},
        {key: 'tumblr',text: 'tumblr',value: 'tumblr',icon: 'tumblr',},
        {key: 'tumblr square',text: 'tumblr square',value: 'tumblr square',icon: 'tumblr square',},
        {key: 'tv',text: 'tv',value: 'tv',icon: 'tv',},
        {key: 'twitch',text: 'twitch',value: 'twitch',icon: 'twitch',},
        {key: 'twitter',text: 'twitter',value: 'twitter',icon: 'twitter',},
        {key: 'twitter square',text: 'twitter square',value: 'twitter square',icon: 'twitter square',},
        {key: 'typo3',text: 'typo3',value: 'typo3',icon: 'typo3',},
        {key: 'uber',text: 'uber',value: 'uber',icon: 'uber',},
        {key: 'uikit',text: 'uikit',value: 'uikit',icon: 'uikit',},
        {key: 'umbrella',text: 'umbrella',value: 'umbrella',icon: 'umbrella',},
        {key: 'underline',text: 'underline',value: 'underline',icon: 'underline',},
        {key: 'undo',text: 'undo',value: 'undo',icon: 'undo',},
        {key: 'undo alternate',text: 'undo alternate',value: 'undo alternate',icon: 'undo alternate',},
        {key: 'uniregistry',text: 'uniregistry',value: 'uniregistry',icon: 'uniregistry',},
        {key: 'universal access',text: 'universal access',value: 'universal access',icon: 'universal access',},
        {key: 'university',text: 'university',value: 'university',icon: 'university',},
        {key: 'unlink',text: 'unlink',value: 'unlink',icon: 'unlink',},
        {key: 'unlock',text: 'unlock',value: 'unlock',icon: 'unlock',},
        {key: 'unlock alternate',text: 'unlock alternate',value: 'unlock alternate',icon: 'unlock alternate',},
        {key: 'untappd',text: 'untappd',value: 'untappd',icon: 'untappd',},
        {key: 'upload',text: 'upload',value: 'upload',icon: 'upload',},
        {key: 'usb',text: 'usb',value: 'usb',icon: 'usb',},
        {key: 'user',text: 'user',value: 'user',icon: 'user',},
        {key: 'user circle',text: 'user circle',value: 'user circle',icon: 'user circle',},
        {key: 'user circle outline',text: 'user circle outline',value: 'user circle outline',icon: 'user circle outline',},
        {key: 'user md',text: 'user md',value: 'user md',icon: 'user md',},
        {key: 'user outline',text: 'user outline',value: 'user outline',icon: 'user outline',},
        {key: 'user plus',text: 'user plus',value: 'user plus',icon: 'user plus',},
        {key: 'user secret',text: 'user secret',value: 'user secret',icon: 'user secret',},
        {key: 'user times',text: 'user times',value: 'user times',icon: 'user times',},
        {key: 'users',text: 'users',value: 'users',icon: 'users',},
        {key: 'ussunnah',text: 'ussunnah',value: 'ussunnah',icon: 'ussunnah',},
        {key: 'utensil spoon',text: 'utensil spoon',value: 'utensil spoon',icon: 'utensil spoon',},
        {key: 'utensils',text: 'utensils',value: 'utensils',icon: 'utensils',},
        {key: 'vaadin',text: 'vaadin',value: 'vaadin',icon: 'vaadin',},
        {key: 'venus',text: 'venus',value: 'venus',icon: 'venus',},
        {key: 'venus double',text: 'venus double',value: 'venus double',icon: 'venus double',},
        {key: 'venus mars',text: 'venus mars',value: 'venus mars',icon: 'venus mars',},
        {key: 'viacoin',text: 'viacoin',value: 'viacoin',icon: 'viacoin',},
        {key: 'viadeo',text: 'viadeo',value: 'viadeo',icon: 'viadeo',},
        {key: 'viadeo square',text: 'viadeo square',value: 'viadeo square',icon: 'viadeo square',},
        {key: 'viber',text: 'viber',value: 'viber',icon: 'viber',},
        {key: 'video',text: 'video',value: 'video',icon: 'video',},
        {key: 'vimeo',text: 'vimeo',value: 'vimeo',icon: 'vimeo',},
        {key: 'vimeo square',text: 'vimeo square',value: 'vimeo square',icon: 'vimeo square',},
        {key: 'vimeo v',text: 'vimeo v',value: 'vimeo v',icon: 'vimeo v',},
        {key: 'vine',text: 'vine',value: 'vine',icon: 'vine',},
        {key: 'vk',text: 'vk',value: 'vk',icon: 'vk',},
        {key: 'vnv',text: 'vnv',value: 'vnv',icon: 'vnv',},
        {key: 'volleyball ball',text: 'volleyball ball',value: 'volleyball ball',icon: 'volleyball ball',},
        {key: 'volume down',text: 'volume down',value: 'volume down',icon: 'volume down',},
        {key: 'volume off',text: 'volume off',value: 'volume off',icon: 'volume off',},
        {key: 'volume up',text: 'volume up',value: 'volume up',icon: 'volume up',},
        {key: 'vuejs',text: 'vuejs',value: 'vuejs',icon: 'vuejs',},
        {key: 'warehouse',text: 'warehouse',value: 'warehouse',icon: 'warehouse',},
        {key: 'wechat',text: 'wechat',value: 'wechat',icon: 'wechat',},
        {key: 'weibo',text: 'weibo',value: 'weibo',icon: 'weibo',},
        {key: 'weight',text: 'weight',value: 'weight',icon: 'weight',},
        {key: 'weixin',text: 'weixin',value: 'weixin',icon: 'weixin',},
        {key: 'whatsapp',text: 'whatsapp',value: 'whatsapp',icon: 'whatsapp',},
        {key: 'whatsapp square',text: 'whatsapp square',value: 'whatsapp square',icon: 'whatsapp square',},
        {key: 'wheelchair',text: 'wheelchair',value: 'wheelchair',icon: 'wheelchair',},
        {key: 'whmcs',text: 'whmcs',value: 'whmcs',icon: 'whmcs',},
        {key: 'wifi',text: 'wifi',value: 'wifi',icon: 'wifi',},
        {key: 'wikipedia w',text: 'wikipedia w',value: 'wikipedia w',icon: 'wikipedia w',},
        {key: 'window close',text: 'window close',value: 'window close',icon: 'window close',},
        {key: 'window close outline',text: 'window close outline',value: 'window close outline',icon: 'window close outline',},
        {key: 'window maximize',text: 'window maximize',value: 'window maximize',icon: 'window maximize',},
        {key: 'window maximize outline',text: 'window maximize outline',value: 'window maximize outline',icon: 'window maximize outline',},
        {key: 'window minimize',text: 'window minimize',value: 'window minimize',icon: 'window minimize',},
        {key: 'window minimize outline',text: 'window minimize outline',value: 'window minimize outline',icon: 'window minimize outline',},
        {key: 'window restore',text: 'window restore',value: 'window restore',icon: 'window restore',},
        {key: 'window restore outline',text: 'window restore outline',value: 'window restore outline',icon: 'window restore outline',},
        {key: 'windows',text: 'windows',value: 'windows',icon: 'windows',},
        {key: 'won sign',text: 'won sign',value: 'won sign',icon: 'won sign',},
        {key: 'wordpress',text: 'wordpress',value: 'wordpress',icon: 'wordpress',},
        {key: 'wordpress simple',text: 'wordpress simple',value: 'wordpress simple',icon: 'wordpress simple',},
        {key: 'wpbeginner',text: 'wpbeginner',value: 'wpbeginner',icon: 'wpbeginner',},
        {key: 'wpexplorer',text: 'wpexplorer',value: 'wpexplorer',icon: 'wpexplorer',},
        {key: 'wpforms',text: 'wpforms',value: 'wpforms',icon: 'wpforms',},
        {key: 'wrench',text: 'wrench',value: 'wrench',icon: 'wrench',},
        {key: 'xbox',text: 'xbox',value: 'xbox',icon: 'xbox',},
        {key: 'xing',text: 'xing',value: 'xing',icon: 'xing',},
        {key: 'xing square',text: 'xing square',value: 'xing square',icon: 'xing square',},
        {key: 'y combinator',text: 'y combinator',value: 'y combinator',icon: 'y combinator',},
        {key: 'yahoo',text: 'yahoo',value: 'yahoo',icon: 'yahoo',},
        {key: 'yandex',text: 'yandex',value: 'yandex',icon: 'yandex',},
        {key: 'yandex international',text: 'yandex international',value: 'yandex international',icon: 'yandex international',},
        {key: 'yelp',text: 'yelp',value: 'yelp',icon: 'yelp',},
        {key: 'yen sign',text: 'yen sign',value: 'yen sign',icon: 'yen sign',},
        {key: 'yoast',text: 'yoast',value: 'yoast',icon: 'yoast',},
        {key: 'youtube',text: 'youtube',value: 'youtube',icon: 'youtube',},
        {key: 'youtube square',text: 'youtube square',value: 'youtube square',icon: 'youtube square',},
    ];

    render() {
        return (
            <Form.Group>
                <Form.Field label={this.props.name} control={Dropdown} placeholder={this.props.name} search fluid selection options={this.tagOptions} width={this.props.width} />
            </Form.Group>
        );
    }
}

IconInput.propTypes = {
  name: PropTypes.string,
  width: PropTypes.number
};

export default IconInput;
